Feature: auto-format in markdown the table through intellij cucumber plugin

  Scenario Template: table-template

  Scenario: table

    Given

      | release name               | category   | sub-type                | tech. version   | src url                                                                       | ci                                                                 | maturity                           | main contributors   | maintained   | Backlog                                                 | HA in AZ   | Multi-az   | Broker included ??  | app usage  | comment                                                                              | Backup/restore ? |
      | -------------------------- | ---------- | ----------------------- | --------------- | ---------                                                                     | -----                                                              | ---------------------------------- | ------------------- | ------------ | --------                                                | ---------- | ---------- | ------------------- | ---------- | ---------                                                                            | ---------------- |
      | P-mysql                    | service    | RDBMS                   | Mysql + galera  | [url](https://github.com/cloudfoundry/cf-mysql-release)                       |                                                                    | commercial                         | pivotal             | yes          | [url](https://www.pivotaltracker.com/n/projects/969486) | yes        | yes        | yes                 | dev        | schema as a service (isolation w.r.t. other workloads)                               | N                |
      | Postgres-docker            | service    | RDBMS                   | pgsql           | [url](http://github.com/cloudfoundry-community/postgresql-docker-boshrelease) |                                                                    | poc                                | Stark & wayne       | ?            |                                                         | no         | no         |                     | dev        |                                                                                      | N                |
      | RDPG                       | service    | RDBMS                   | pgsql           | [url](https://github.com/starkandwayne/rdpg-boshrelease)                      | [url](http://ci.starkandwayne.com:8080/pipelines/rdpg-boshrelease) | poc                                | Stark & wayne       | ?            |                                                         | no         | no         |                     | dev        |                                                                                      | N                |
      | Cassandra                  | service    | NOSQL                   | Cassandra 1.2.3 | [url](https://github.com/emc-cloudfoundry/cassandra-cf-service-boshrelease)   |                                                                    | runs-in-prod                       | Emc-content         | semi         |                                                         | yes        | yes        |                     | prod       |                                                                                      | N                |
      | Riak-cs                    | service    | Object storage          |                 | [url](https://github.com/cloudfoundry/cf-riak-cs-release)                     |                                                                    | commercial                         | pivotal             | yes          | [url](https://www.pivotaltracker.com/n/projects/969486) | yes        | planned    | yes                 | prod       |                                                                                      | N                |
      | P-redis                    | service    | messaging               | redis           |                                                                               |                                                                    | commercial                         | pivotal             | yes          |                                                         | yes        |            | yes                 | prod       |                                                                                      | N                |
      | Memcache-hazelcast         | service    | Caching                 | hazelcast       | [url](https://github.com/cloudfoundry-community/memcache-release)             |                                                                    | runs-in-prod                       | lds                 | yes          |                                                         | yes        |            | yes                 | prod       |                                                                                      | N                |
      | Swift                      | service    | Object storage          |                 | [url](https://github.com/emc-cloudfoundry/swift-boshrelease)                  |                                                                    | runs-in-prod                       | Emc-content         | semi         |                                                         | yes        |            | no                  | prod       |                                                                                      | N                |
      | P-rabbit                   | service    |                         | Rabbit-mq       | [url](https://github.com/pivotal-cf/cf-rabbitmq-release)                      |                                                                    | commercial                         | pivotal             | yes          | [url](https://www.pivotaltracker.com/n/projects/969486) | yes        |            | yes                 | prod       |                                                                                      | N                |
      | Mongo-db service contrib   | service    |                         |                 |                                                                               |                                                                    | runs-in-prod                       | pivotal             | no           |                                                         | no         |            | v1                  | dev        | [alternative broker](https://github.com/pivotalservices/cf-logsearch-service-broker) | N                |
      | Log-search                 | service    | Log & metrics storage   | ELK             | [url](http://logsearch.io/)                                                   |                                                                    | runs-in-prod                       | city bank           | yes          |                                                         | yes        |            | no                  | dev        |                                                                                      | N                |
      | hadoop                     | service    | BIG DATA                | Hadoop 2.2.0    | [url](http://bosh.io/releases/github.com/cf-platform-eng/hadoop-boshrelease)  |                                                                    | poc                                |                     | no           |                                                         | yes        |            | no                  |            |                                                                                      | N                |
      | gemfire                    | service    | NOSQL                   | gemfire         | [url](https://github.com/Pivotal-Field-Engineering/gemfire-bosh-release)      |                                                                    | poc (commercial version private)   | pivotal             | no           |                                                         |            |            |                     |            |                                                                                      | N                |
      | crate                      | service    | nosql                   | crate           | [url](https://github.com/cloudfoundry-community/crate-boshrelease)            |                                                                    | poc                                | pivotal             | semi         |                                                         | ?          |            |                     | dev        |                                                                                      | N                |
      | consul                     | service    | discovery               | consul          | [url](https://github.com/cloudfoundry-community/consul-boshrelease)           |                                                                    | Opensource,??                      | stark & wayne       | yes          |                                                         | ?          |            |                     |            |                                                                                      |                  |
      | HANA                       | service    | db                      |                 | [url](https://github.com/cloudfoundry-community/cf-hanadb-broker)             |                                                                    | ?                                  | SAP                 | no           |                                                         |            |            |                     |            |                                                                                      |                  |
      | clam-av                    | service    | anti-virus scanner      |                 | [url](https://github.com/emc-cloudfoundry/clamav-boshrelease)                 |                                                                    |                                    | Emc-content         |              |                                                         |            |            |                     |            |                                                                                      |                  |
      | kafka                      | service    | messaging               |                 | [url](https://github.com/pivotal-cf-experimental/kafka-release)               |                                                                    | poc?                               | Pivotal             |              |                                                         |            |            |                     |            |                                                                                      |                  |
      | influxdb                   | service    | Time series DB          |                 | [url](https://github.com/pivotal-cf-experimental/influxdb-release)            |                                                                    | poc                                | Pivotal             |              |                                                         |            |            |                     |            |                                                                                      |                  |
      |                            |            |                         |                 |                                                                               |                                                                    |                                    |                     |              |                                                         |            |            |                     |            |                                                                                      |                  |
      | concourse                  | ci         |                         | consourse       | [url](http://concourse.ci/deploying-with-bosh.html)                           |                                                                    |                                    |                     |              |                                                         |            |            |                     |            |                                                                                      |                  |
      | jenkins                    | ci         |                         | jenkins         | [url](https://github.com/cloudfoundry-community/jenkins-boshrelease)          |                                                                    | Opensource,??                      | rakuten,            | yes          |                                                         |            |            |                     |            |                                                                                      |                  |
      |                            |            |                         |                 |                                                                               |                                                                    |                                    |                     |              |                                                         |            |            |                     |            |                                                                                      |                  |
      | docker                     | infra-frmk |                         |                 | [url](https://github.com/cf-platform-eng/docker-boshrelease)                  |                                                                    | poc                                | pivotal             |              |                                                         |            | no         | yes                 | n/a        |                                                                                      |                  |
      | deployment-vm-boshrelease  | running-cf | cf ops CLIs             |                 | [url](https://github.com/emc-cloudfoundry/deployment-vm-boshrelease)          |                                                                    | runs-in-prod                       | Emc-content         |              |                                                         |            |            |                     |            |                                                                                      |                  |
      | mesos                      | infra-frmk |                         |                 | [url](http://bosh.io/releases/github.com/cf-platform-eng/mesos-boshrelease)   |                                                                    | poc                                | pivotal             |              |                                                         |            |            |                     |            |                                                                                      |                  |
      |                            |            |                         |                 |                                                                               |                                                                    |                                    |                     |              |                                                         |            |            |                     |            |                                                                                      |                  |
      | admin-ui                   | running-cf |                         |                 | [url](https://github.com/cloudfoundry-incubator/admin-ui)                     |                                                                    | runs-in-prod                       |                     |              |                                                         |            |            |                     |            |                                                                                      |                  |
